- name: Executar comandos de pós-deploy no servidor
  run: |
    ssh -o StrictHostKeyChecking=no -p "${{ secrets.SSH_PORT }}" "${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}" "
      set -euo pipefail
      APP_PATH='${{ secrets.HOSTINGER_APP_PATH }}'
      WEBROOT='${{ secrets.HOSTINGER_WEBROOT }}'

      cd \$APP_PATH

      echo '→ Limpando caches antigos...'
      php artisan optimize:clear

      echo '→ Rodando migrations (forçado em produção)...'
      php artisan migrate --force

      echo '→ Recriando caches...'  # depois das migrations
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache

      echo '→ Permissões e storage...'
      chmod -R 775 storage bootstrap/cache || true
      rm -rf \$WEBROOT/storage || true
      ln -s \$APP_PATH/storage/app/public \$WEBROOT/storage || true

      echo '→ Garantindo index.php no webroot...'
      cat > \"\$WEBROOT/index.php\" <<'EOF'
<?php
define('LARAVEL_START', microtime(true));
require __DIR__.'/../curriculogamer/vendor/autoload.php';
$app = require __DIR__.'/../curriculogamer/bootstrap/app.php';
$kernel = $app->make(Illuminate\Contracts\Http\Kernel::class);
$response = $kernel->handle(
    $request = Illuminate\Http\Request::capture()
)->send();
$kernel->terminate($request, $response);
EOF

      echo '→ .htaccess...'
      cat > \"\$WEBROOT/.htaccess\" <<'EOF'
<IfModule mod_rewrite.c>
  <IfModule mod_negotiation.c>
    Options -MultiViews -Indexes
  </IfModule>
  RewriteEngine On
  RewriteCond %{REQUEST_FILENAME} !-d
  RewriteCond %{REQUEST_FILENAME} !-f
  RewriteRule ^ index.php [L]
</IfModule>
EOF

      echo '→ Health-check...'
      (curl -sSf -I https://curriculogamer.com.br >/dev/null && echo 'OK') || { 
        echo 'Falha no health-check. Últimas linhas do log:'
        tail -n 200 storage/logs/laravel.log || true
        exit 1
      }

      echo '✅ Deploy concluído com sucesso!'
    "
