name: Deploy to Hostinger

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_mysql, bcmath, curl
          tools: composer

      - name: Install Composer deps (no-dev)
        run: composer install --no-interaction --no-dev --prefer-dist --optimize-autoloader

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install NPM deps
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Prepare deployment package
        run: |
          mkdir -p deploy_package
          rsync -av \
            --exclude=".git" \
            --exclude="node_modules" \
            --exclude="tests" \
            --exclude=".github" \
            --exclude="storage/logs/*.log" \
            ./ deploy_package/

      - name: Add SSH key
        shell: bash
        run: |
          set -e
          mkdir -p ~/.ssh
          printf "%s\n" "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -p 65002 -H "${{ secrets.HOSTINGER_HOST }}" >> ~/.ssh/known_hosts
          ls -la ~/.ssh

      # 1º sync: código inteiro para a pasta do app (curriculogamer)
      - name: Upload app (curriculogamer)
        run: |
          rsync -az -e "ssh -p 65002" --delete \
            deploy_package/ \
            "${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}:${{ secrets.HOSTINGER_APP_PATH }}/"

      # 2º sync: conteúdo do public/ para o webroot (public_html)
      - name: Upload web assets (public -> public_html)
        run: |
          rsync -az -e "ssh -p 65002" --delete \
            deploy_package/public/ \
            "${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}:${{ secrets.HOSTINGER_WEBROOT }}/"

      - name: Post-deploy (migrate, caches, permissões, .htaccess)
        run: |
          ssh -p 65002 "${{ secrets.HOSTINGER_USER }}@${{ secrets.HOSTINGER_HOST }}" "\
            set -e && \
            cd '${{ secrets.HOSTINGER_APP_PATH }}' && \
            php artisan config:clear && \
            php artisan migrate --force && \
            php artisan optimize && \
            php artisan storage:link || true && \
            chmod -R 775 storage bootstrap/cache && \
            cp public/.htaccess '${{ secrets.HOSTINGER_WEBROOT }}'/.htaccess \
          "
